---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Bereid je voor op Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Inleiding
  - 
    title: Wat is een Astro Pi?
  - 
    title: Toon een bericht en kies een naam voor de nieuwe Astro Pi computers
    completion:
      - engaged
  - 
    title: Voeg wat kleur toe
  - 
    title: Toon een afbeelding
    completion:
      - internal
  - 
    title: Meet de luchtvochtigheid
