---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Voorbereiding voor Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
- title: Introductie
- title: Wat is een Astro Pi?
- title: Laat een boodschap zien en kies een naam voor de nieuwe Astro Pi-computers
  completion:
  - engaged
- title: Voeg er wat kleur aan toe
- title: Laat een beeld zien
- title: Meet de vochtigheid
- title: Reageer op vochtigheid
- title: Je project indienen
  completion:
  - internal
- title: 'Uitdaging: meer Aspro Pi projecten'
