---
title: 'Astro Pi: Missão Zero'
hero_image: images/banner.png
description: Prepara-te para a Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Introdução
  - 
    title: O que é um Astro Pi?
  - 
    title: Exibe uma mensagem e escolhe um nome para o novo computador do Astro Pi
    completion:
      - engaged
  - 
    title: Adiciona um pouco de cor
  - 
    title: Mostrar uma imagem
    completion:
      - internal
  - 
    title: Medir a humidade
