---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Valmistaudu Mission Zeroon
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
- title: Esittely
  completion: engaged
- title: Mikä on Astro Pi?
- title: Näytä viesti ja valitse nimi uusille Astro Pi -tietokoneille
- title: Lisää jonkun verran väriä
- title: Näytä kuva
- title: Mittaa ilmankosteus
- title: Reagoi ilmankosteuteen
- title: Lähetä osallistumisilmoituksesi
  completion: internal
- title: Mitä seuraavaksi — lisää Astro Pi -projekteja
