---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Pregătește-te pentru Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
- title: Introducere
  completion: engaged
- title: Ce este Astro Pi?
- title: Afișează un mesaj și alege un nume pentru noile calculatoare Astro Pi
- title: Adaugă culoare
- title: Afișează o imagine
- title: Măsoară umiditatea
- title: Reacționează la umiditate
- title: Trimite programul tău
  completion: internal
- title: Ce urmează — mai multe proiecte Astro Pi
