---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Pripravite se na Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
- title: Uvod
  completion: engaged
- title: Kaj je Astro Pi?
- title: Prikažite sporočilo in izberite ime za nove Astro Pi računalnike
- title: Dodajte barve
- title: Prikažite sliko
- title: Izmerite vlažnost
- title: Prikažite vlažnost
- title: Pošljite svoj prispevek
  completion: internal
- title: 'Izziv: več projektov Astro Pi'
