---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Készülj fel a Mission Zeróra!
listed: true
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Bevezetés
  - 
    title: Mi az az Astro Pi?
  - 
    title: Display an image
    completion:
      - engaged
  - 
    title: Sense a colour
  - 
    title: Submit your entry
    completion:
      - internal
  - 
    title: What next — more Astro Pi projects
