---
title: 'Astro Pi: Misja Zero'
hero_image: images/banner.png
description: Przygotuj się do Misji Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Wprowadzenie
  - 
    title: Czym jest Astro Pi?
  - 
    title: Wyświetl wiadomość i wybierz nazwę dla nowych komputerów Astro Pi
    completion:
      - engaged
  - 
    title: Dodawanie koloru
  - 
    title: Wyświetlanie obrazków
    completion:
      - internal
  - 
    title: Pomiar wilgotności
