---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Förbered dig för Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: You will make
  - 
    title: Vad är en Astro Pi?
  - 
    title: Display an image
    completion:
      - engaged
  - 
    title: Sense a colour
  - 
    title: Submit your entry
    completion:
      - internal
  - 
    title: What next — more Astro Pi projects
