---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Προετοιμάσου για το Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Εισαγωγή
  - 
    title: Τι είναι το Astro Pi;
  - 
    title: Display an image
    completion:
      - engaged
  - 
    title: Προσθήκη χρώματος
  - 
    title: Εμφάνιση εικόνας
    completion:
      - internal
  - 
    title: Μέτρηση της υγρασίας
