---
title: 'Astro Pi : Mission Zero'
hero_image: images/banner.png
description: Se préparer pour Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Introduction
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Add some colour
    completion:
      - engaged
  - 
    title: Ajouter de la couleur
  - 
    title: Afficher une image
  - 
    title: Mesurer l'humidité
    completion:
      - internal
  - 
    title: Réagir à l'humidité
